#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine: install Nginx, listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Holberton School
# /redirect_me is redirecting to another page -> https://www.youtube.com/watch?v=QH2-TGUlwu4
# The redirection must be a “301 Moved Permanently”
# Configure a Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# The page must return an HTTP 404 error code

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "<h1>Ceci n'est pas une page.</h1>" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/listen 80 default_server/ a\ \terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx start
