#!/usr/bin/env bash
# Scripts that displays the content of the file /etc/passwd
# username, user id, Home directory path for the user
IFS=$':'
while read -r USER_NAME PASSWD USER_ID GID UID_INFO HOME_DIR CMD_SHELL
do
    printf "The user %s is part of the %s gang, " "$USER_NAME" "$GID"
    printf "lives in %s and rides %s. " "$HOME_DIR" "$CMD_SHELL"
    printf "%s's place is protected by the passcode %s, " "$USER_ID" "$PASSWD"
    printf "more info about the user here: %s\n" "$UID_INFO"
done < /etc/passwd
