#!/usr/bin/env bash
# Displays the content /etc/passwd, using the while loop + IFS as a story

while IFS=":" read -r USER_NAME PASSWD USER_ID GROUP_ID UID_INFO HOME_DIR CMD_SHELL
do
    echo "The user $USER_NAME is part of the $GROUP_ID gang, lives in $HOME_DIR and \
rides $CMD_SHELL. $USER_ID's place is protected by the passcode $PASSWD, more \
info about the user here: $UID_INFO"
done < /etc/passwd
