#!/usr/bin/env bash
# Script that displays Holberton School 10 times, but for the 9th iteration,
# displays Holberton School and then Hi on a new line.
counter=0
while [ $counter -lt 10 ]
do
	if [[ $counter -eq 9 ]]
	then
		echo "Hi"
	fi
	echo "Holberton School"
	counter=$(( counter + 1 ))
done
