#!/usr/bin/env bash
# Script that loops from 1 to 10 and display messages acording number
counter=1
while [ $counter -le 10 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	counter=$(( counter + 1 ))
done
