#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes
HOUR=0
while [ $HOUR -le 12 ]; do
    MIN=1
    echo "Hour: $HOUR"
    while [ $MIN -le 59 ]; do
	echo $MIN
	MIN=$(( MIN + 1 ))
	done
    HOUR=$(( HOUR + 1 ))
done
