#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes
counter=0
hour=0
while [ $hour -le 12 ]; do
    if [ $(( counter % 60 )) -eq 0 ]
    then
	echo "Hour: $hour"
	hour=$(( hour + 1))
	counter=0
    else
	echo $counter
    fi
    counter=$(( counter + 1 ))
done
