#!/usr/bin/env bash
# Script that displays the content of the current directory in
# list format with only the part of the name after the first dash
for filename in *; do
    echo "${filename}"| cut -d "-" -f2
done
