#!/usr/bin/env bash
# Configures ufw settings and allow: 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)
# sudo ufw status verbose
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
