#!/usr/bin/env bash
# Set a container so that Nginx is running as the nginx user.
pkill -9 apache2
chown nginx:nginx /etc/nginx/
chmod 744 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default 
sudo -u nginx service nginx restart
